-- Tests skipped by the C regression suite.
-- Remove an entry manually to re-enable the test.
-- gpu: C tests whose GPU variant timed out (CPU variant still runs).
return {
   ignore = {
      tests = {
         "rt_can_pb_bgk_surf_cylindrical_sodshock_im_1x3v_p2",
         "rt_can_pb_bgk_surf_annulus_sodshock_im_2x2v_p2",
         "rt_can_pb_bgk_surf_sphere_sodshock_im_2x2v_p1",
         "rt_vlasov_neut_bgk_sodshock_1x3v_p2",
         "rt_can_pb_bgk_surf_sphere_sodshock_im_1x2v_p2",
         "rt_can_pb_ex_bgk_surf_flat_sq_ic",
         "rt_can_pb_bgk_surf_sphere_sodshock_im_2x2v_p2",
         "rt_escreen_sr",
         "rt_hyper_vlasov_tm",
         "rt_vlasov_kerntm",
         "rt_vlasov_moments",
         "rt_can_pb_bgk_surf_cylindrical_sodshock_im_3x3v_p1",
         "rt_can_pb_bgk_surf_toroidal_sodshock_im_3x3v_p1",
         "rt_vlasov_lbo_cross_1x2v_p2",
         "rt_vp_sheath_Aext_1x2v_p2",
         "rt_vlasov_neut_lbo_sodshock_1x3v_p2",
         "rt_can_pb_neut_bgk_sodshock_im_1x2v_p2",
         "rt_vlasov_sheath_bgk_1x1v_p2",
         "rt_can_pb_bgk_surf_annulus_sodshock_im_2x2v_p1",
         "rt_vlasov_weibel_2x2v_p2",
         "rt_vlasov_es_shock_lbo_1x3v",
         "rt_can_pb_bgk_surf_toroidal_sodshock_im_2x3v_p2",
         "rt_dg_euler_kh_2d",
         "rt_can_pb_bgk_surf_annulus_sodshock_im_1x2v_p2",
         "rt_vp_sheath_Bext_1x2v_p2",
         "rt_diffusion_1x",
      },
      gpu = {
         "rt_dg_5m_mom_beach_p2",
         "rt_vlasov_sr_neut_bgk_sodshock_1x1v_p2",
         "rt_vlasov_sr_freestream",
         "rt_dg_diffusion_gen_3x",
         "rt_can_pb_bgk_surf_toroidal_sodshock_im_3x3v_p1",
         "rt_escreen_sr",
         "rt_dg_5m_mom_beach_p3",
         "rt_hyper_vlasov_tm",
         "rt_dg_diffusion_gen_2x",
         "rt_diffusion_1x",
         "rt_can_pb_bgk_surf_cylindrical_sodshock_im_3x3v_p1",
         "rt_vlasov_sr_bgk_relax_1x1v_p2",
         "rt_vlasov_kerntm",
         "rt_diffusion_2x",
      },
   },
   moat = {
      "rt_vlasov_landau_damping_1x1v_p2", "rt_vlasov_twostream_p2",
      "rt_vlasov_es_shock", "rt_vlasov_bgk_relax_1x1v_p2",
   },
   parallel = {
      { name = "rt_vlasov_twostream_p2", cuts = { 4 } },
      { name = "rt_vlasov_weibel_2x2v_p2", cuts = { 2, 2 } },
   },
}
