#include <gkyl_nc_hamil_gen_vol_comps_kernels.h> 
#include <gkyl_vlasov_kernels.h> 
GKYL_CU_DH GKYL_NOINLINE static void dot_pb_2x3v_ser_p2(const double *list_1, const double *list_2, double* GKYL_RESTRICT out) 
{ 
  for (int i = 0; i<112; ++i) out[0] += list_1[i]*list_2[i]; 
} 
  
GKYL_CU_DH GKYL_NOINLINE static void zero_pb_list(double *pb_list) 
{ 
  for (int i = 0; i<112; ++i) pb_list[i] = 0.0; 
} 
  
GKYL_CU_DH void vlasov_nc_hamil_vel_dense_vol_2x3v_ser_p2(const double *w, const double *dxv, const double *vmap,
  const double *jacob_pos, const double *jacob_vel, const double *poisson_tensor_conf, const double *hamil, const double *f,
  const double *f_no_J, double* GKYL_RESTRICT out) 
{ 
  double alphai[112] = {0.0}; 
  double bracket_w_Hi[112] = {0.0}; 
  for (int dir = 0; dir<5; ++dir) { 
    // Compute the per-direction charateristic 
    zero_pb_list(alphai); 
    vlasov_nc_hamil_vel_dense_vol_alpha_2x3v_ser_p2(w, dxv, dir, vmap, jacob_pos, jacob_vel, poisson_tensor_conf, hamil, alphai); 
    
    // Compute the modal basis backet coeffcients, accumulate the outputs 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp0_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[0]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp1_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[1]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp2_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[2]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp3_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[3]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp4_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[4]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp5_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[5]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp6_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[6]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp7_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[7]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp8_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[8]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp9_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[9]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp10_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[10]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp11_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[11]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp12_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[12]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp13_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[13]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp14_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[14]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp15_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[15]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp16_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[16]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp17_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[17]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp18_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[18]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp19_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[19]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp20_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[20]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp21_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[21]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp22_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[22]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp23_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[23]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp24_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[24]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp25_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[25]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp26_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[26]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp27_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[27]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp28_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[28]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp29_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[29]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp30_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[30]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp31_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[31]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp32_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[32]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp33_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[33]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp34_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[34]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp35_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[35]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp36_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[36]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp37_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[37]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp38_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[38]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp39_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[39]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp40_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[40]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp41_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[41]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp42_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[42]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp43_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[43]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp44_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[44]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp45_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[45]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp46_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[46]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp47_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[47]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp48_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[48]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp49_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[49]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp50_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[50]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp51_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[51]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp52_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[52]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp53_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[53]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp54_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[54]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp55_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[55]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp56_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[56]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp57_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[57]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp58_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[58]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp59_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[59]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp60_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[60]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp61_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[61]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp62_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[62]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp63_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[63]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp64_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[64]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp65_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[65]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp66_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[66]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp67_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[67]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp68_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[68]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp69_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[69]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp70_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[70]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp71_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[71]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp72_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[72]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp73_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[73]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp74_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[74]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp75_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[75]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp76_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[76]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp77_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[77]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp78_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[78]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp79_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[79]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp80_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[80]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp81_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[81]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp82_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[82]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp83_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[83]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp84_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[84]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp85_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[85]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp86_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[86]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp87_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[87]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp88_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[88]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp89_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[89]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp90_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[90]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp91_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[91]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp92_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[92]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp93_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[93]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp94_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[94]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp95_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[95]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp96_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[96]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp97_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[97]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp98_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[98]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp99_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[99]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp100_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[100]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp101_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[101]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp102_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[102]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp103_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[103]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp104_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[104]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp105_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[105]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp106_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[106]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp107_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[107]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp108_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[108]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp109_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[109]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp110_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[110]); 
    zero_pb_list(bracket_w_Hi); 
    vlasov_nc_hamil_gen_vol_comp111_2x3v_ser_p2(w, dxv, dir, jacob_pos, jacob_vel, alphai, bracket_w_Hi); 
    dot_pb_2x3v_ser_p2(f, bracket_w_Hi, &out[111]); 
    
  } 
} 
