-- Tests skipped by the Lua regression suite.
-- Remove an entry manually to re-enable the test.
-- gpu: Lua tests whose GPU variant timed out (CPU variant still runs).
return {
   tests = {
      "rt_can_pb_bgk_surf_cylindrical_sodshock_im_3x3v_p1",
      "rt_can_pb_ex_bgk_surf_flat_sq_ic",
      "rt_can_pb_bgk_surf_annulus_sodshock_im_2x2v_p2",
      "rt_can_pb_bgk_surf_sphere_sodshock_im_1x2v_p2",
      "rt_can_pb_bgk_surf_cylindrical_sodshock_im_1x3v_p2",
      "rt_can_pb_bgk_surf_sphere_sodshock_im_2x2v_p2",
      "rt_can_pb_bgk_surf_sphere_sodshock_im_2x2v_p1",
      "rt_can_pb_bgk_surf_toroidal_sodshock_im_3x3v_p1",
      "rt_can_pb_neut_bgk_sodshock_im_1x2v_p2",
      "rt_can_pb_bgk_surf_annulus_sodshock_im_1x2v_p2",
      "rt_vp_sheath_Bext_1x2v_p2",
      "rt_vlasov_es_shock_lbo_1x3v",
      "rt_vlasov_neut_lbo_sodshock_1x3v_p2",
      "rt_vlasov_weibel_2x2v_p2",
      "rt_vlasov_sheath_bgk_1x1v_p2",
      "rt_can_pb_bgk_surf_toroidal_sodshock_im_2x3v_p2",
      "rt_can_pb_bgk_surf_annulus_sodshock_im_2x2v_p1",
      "rt_vlasov_lbo_cross_1x2v_p2",
      "rt_vlasov_neut_bgk_sodshock_1x3v_p2",
      "rt_can_pb_neut_bgk_sodshock_im_1x2v_p1",
      "rt_vlasov_weibel_lbo_2x2v_p2",
      "rt_vlasov_bgk_relax_1x3v_p2",
      "rt_can_pb_bgk_surf_sphere_sodshock_im_1x2v_p1",
      "rt_dg_diffusion_gen_3x",
      "rt_can_pb_distorted_mesh_ic_2x2v_p2",
      "rt_can_pb_newtonian_orbits",
      "rt_can_pb_free_streaming_surf_sphere",
      "rt_vlasov_lbo_relax_1x3v_p2",
      "rt_can_pb_bgk_surf_toroidal_sodshock_im_2x3v_p1",
      "rt_can_pb_bgk_surf_cylindrical_sodshock_im_2x3v_p1",
      "rt_can_pb_bgk_surf_cylindrical_sodshock_im_1x3v_p1",
      "rt_vlasov_sr_twostream_1x3v",
      "rt_dg_5m_mom_beach_p2",
   },
   gpu = {
   },
}
